import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Head from "next/head";
import Script from "next/script";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Script src="https://developers.kakao.com/sdk/js/kakao.js"></Script>
    <body className={inter.className}>{children}</body>
    </html>
  )
}
